apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: enterprise-multicloud-workloads
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: enterprise-core
  source:
    repoURL: 'https://github.com/FreeFades2Black/enterprise-multicloud-gitops-zerotrust.git'
    targetRevision: HEAD
    path: helm/enterprise-app
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: production-workloads
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
